/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "whatsup.h"

bool_t
xdr_record (XDR *xdrs, record *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->first_num))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->second_num))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_message (XDR *xdrs, message *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->destination, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->origin, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->message, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_contacts (XDR *xdrs, contacts *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->persons, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->groups, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user (XDR *xdrs, user *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->name, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->ip, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
